basePath: /
host: 121.166.4.186:8128
info:
  contact: {}
  title: EcoScanner API Docs with Swagger
  version: "1.0"
paths:
  /board:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 게시글 번호
        in: query
        name: boardId
        required: true
        type: integer
      - description: 회원 번호
        in: query
        name: memberNo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 게시글 삭제
      tags:
      - Board
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 게시판 목록 조회
      tags:
      - Board
  /board/post:
    get:
      consumes:
      - application/json
      parameters:
      - description: 게시글 번호
        in: query
        name: boardId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 게시글 조회
      tags:
      - Board
    post:
      consumes:
      - application/json
      parameters:
      - description: 게시글 번호
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: 회원 번호
        in: body
        name: memberNo
        required: true
        schema:
          type: integer
      - description: 게시글 제목
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: 게시글 내용
        in: body
        name: contents
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 게시글 수정
      tags:
      - Board
    put:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: body
        name: memberNo
        required: true
        schema:
          type: integer
      - description: 게시글 제목
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: 게시글 내용
        in: body
        name: contents
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 게시글 작성
      tags:
      - Board
  /member:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 회원 목록 조회
      tags:
      - User
  /product/{productId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: SKU
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 상품 상세 조회
      tags:
      - Product
  /product/compare:
    get:
      consumes:
      - application/json
      parameters:
      - description: SKU
        in: query
        name: productId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 상품 비교
      tags:
      - Product
  /product/search/{productName}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 검색할 상품 이름
        in: path
        name: productName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 상품 검색
      tags:
      - Product
  /productsimple:
    get:
      consumes:
      - application/json
      parameters:
      - description: 페이지 번호
        in: query
        name: page
        type: integer
      - description: 상품 개수
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 상품 목록 조회
      tags:
      - Product
  /review:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 후기 게시글 번호
        in: query
        name: reviewId
        required: true
        type: integer
      - description: 회원 번호
        in: query
        name: memberNo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 후기 삭제
      tags:
      - Review
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 후기 목록 조회
      tags:
      - Review
  /review/post:
    post:
      consumes:
      - application/json
      parameters:
      - description: 후기 게시글 번호
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: 회원 번호
        in: body
        name: memberNo
        required: true
        schema:
          type: integer
      - description: 후기 내용
        in: body
        name: contents
        required: true
        schema:
          type: string
      - description: 후기 평점
        in: body
        name: reviewRating
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 후기 수정
      tags:
      - Review
    put:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: body
        name: memberNo
        required: true
        schema:
          type: integer
      - description: SKU
        in: body
        name: productId
        required: true
        schema:
          type: integer
      - description: 후기 내용
        in: body
        name: contents
        required: true
        schema:
          type: string
      - description: 후기 평점
        in: body
        name: reviewRating
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 후기 작성
      tags:
      - Review
  /seller:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 기업 목록 조회
      tags:
      - Seller
  /wishlist/{memberNo}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: path
        name: memberNo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 찜 목록 조회
      tags:
      - User
  /wishlist/{type}/{memberno}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: path
        name: memberNo
        required: true
        type: integer
      - description: 상품 or 기업 선택
        in: path
        name: itemtype
        required: true
        type: string
      - description: 전체 삭제 or 특정 항목 삭제
        in: query
        name: allOrNot
        required: true
        type: string
      - description: SKU or 기업 번호
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 찜 목록 삭제
      tags:
      - User
  /wishlist/product:
    put:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: query
        name: memberNo
        required: true
        type: integer
      - description: SKU
        in: query
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 찜 상품 추가
      tags:
      - User
  /wishlist/seller:
    put:
      consumes:
      - application/json
      parameters:
      - description: 회원 번호
        in: query
        name: memberNo
        required: true
        type: integer
      - description: 기업 번호
        in: query
        name: sellerId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: 찜 기업 추가
      tags:
      - User
swagger: "2.0"
